### ISSUE TITLE
secure-cli run jwt example failed

### ISSUE THREAD

**Issue by windyboy** [goadesign/examples#10]
./secure-cli --key eyJhbGciOiJSUz[15/301$
R5cCI6IkpXVCJ9.eyJhdWQiOiJBdWRpZW5jZSIsImV4cCI6MTQ3MzM5MzAxNCwiaWF0IjoxNDczMzkyNDE0LCJpc3MiOiJJc3N1ZXIiLCJqdGkiOiI3ODU5YWRhYy02MTk0LTRlMTUtODFkMy0wZTI5NzNlOWQ
3ZDciLCJuYmYiOjIsInNjb3BlcyI6ImFwaTphY2Nlc3MiLCJzdWIiOiJzdWJqZWN0In0.kEB3aXKq9cPO3P9jELHj5MD6Xz6nbafuuankOT5IQTSioWrHPQROjlNzqPM4Rcfp05qcGIYVIvdSkkPMRZKl2Oci7
-gShsu7m0gsG7KFyOKtCw4Hwq21F7nNAQg29IXe5c2sxVa2QAQmK_eiAjWSDpuhHcq9J0iC6DFQgTVJ-JukvYZJYXqm1kn9qoyyJ2gSA6YggxxzZ2WKvdKFiaYB4Wmdvkeeef0S1srRd91OqF--G1I82-7NIOB
Gl-NgzGH7L5e1VUIgWnK5aizM4bLTTNDdf4G7jc4uCc7Pk8IKzFKocAlQT6ARGv1YuS5Govyx1HgUSUcMWi4hnWwHQiW2zA secure jwt
2016/09/09 11:40:55 [EROR] argument parse failed err=strconv.ParseBool: parsing "": invalid syntax

I check secure-cli source code, there is only one boolean var.
line 29:
app.PersistentFlags().BoolVar(&c.Dump, "dump", false, "Dump HTTP request and response.")

then I add --dump option, try to run again, the error is not gone.

I don't know if there is bug in "github.com/spf13/cobra"

**Comment by raphael** [comment]
This issue is fixed in the latest goa...
