### ISSUE TITLE
Editablegrid integration please

### ISSUE THREAD

**Issue by suntong** [goadesign/examples#13]
The [EditableGrid](http://www.editablegrid.net/en/) is 

> an open source JavaScript library aimed at turning tables into fully editable components. Its API is focused on simplicity : **only a few lines of code** are necessary to get your first editable grid up and running.

Together with goa, the two make perfect tool for a quick CRUD system. 
So please provide an example that integrates well with [EditableGrid](http://www.editablegrid.net/en/).

Thanks

**Comment by raphael** [comment]
Would love a PR but I don't have the knowledge of time required to provide one myself.
