### ISSUE TITLE
Appengine Example : Unable to use make commond

### ISSUE THREAD

**Issue by KashyakSupport** [goadesign/examples#23]
Hi ,

I am using windows and installed Google SDK and get this appengine example folder to src folder,

In **Makefile** , I have mentioned the path which is in **src** folder
> REPO:=examples-master/appengine

Then I have run the below command and getting error 

> Make Example 

Error:
`'make' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by raphael** [comment]
Please make sure you have the `make` tool installed. I'm surprised it's not available by default - what OS are you using? Windows?

**Comment by KashyakSupport** [comment]
I am using windows 10 .

**Comment by raphael** [comment]
Using the Makefile requires a `make` tool. There are different ways to install make on Windows, such as WSL or Cygwin.
