### ISSUE TITLE
security/auth.go is out of date with goa v3

### ISSUE THREAD

**Issue by eric-isakson** [goadesign/examples#53]
Noticed this while trying to reproduce an example to look at https://github.com/goadesign/goa/issues/2116

The security example builds but has a runtime panic.

$ cd security/
$ GO111MODULE=on go build ./cmd/multi_auth
$ ./multi_auth 
panic: interface conversion: *multiauth.securedServiceSvc is not securedservice.Auther: missing method APIKeyAuth

goroutine 1 [running]:
goa.design/examples/security/gen/secured_service.NewEndpoints(0xa80200, 0xc0000ac568, 0x0)
        /home/eric/go/src/goa.design/examples/security/gen/secured_service/endpoints.go:30 +0x59
main.main()
        /home/eric/go/src/goa.design/examples/security/cmd/multi_auth/main.go:53 +0x32a

No time to fix it tonight, I'll find a few minutes to create a PR tomorrow.

**Comment by raphael** [comment]
Nice catch! thank you for looking into it.
