### ISSUE TITLE
security/auth.go is not generated by 3.0.8 later

### ISSUE THREAD

**Issue by akm** [goadesign/examples#60]
```
cd path/to/examples/security
rm auth.go
goa example goa.design/examples/security/design
```

I expect auth.go is generated but it was not.
I changed `goa.design/goa/v3 v3.0.9` to `goa.design/goa/v3 v3.0.7`  in go.mod and try the previous steps again, auth.go is generated.

**Comment by tchssk** [comment]
See https://github.com/goadesign/goa/issues/2441.

**Comment by akm** [comment]
@tchssk Thanks!
